hackathon_config:
  start_at: 08-01-2021 12:00:00 +0800
  end_at: 09-01-2021 12:00:00 +0800
  devpost_link: https://hacknroll2021.devpost.com
  checks:
    - substantial_authors_contributions
    - commit_only_during_hackathon
    - only_valid_authors
    - repo_not_forked
#    - no_commit_overlap_with_other_user_project
#    - source_code_not_similar_to_other_user_project
